# Generated by Django 2.2.18 on 2021-12-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
